### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by lovawins** [maxaakre/air-bean-firepirates#43]
Bakgrundsfärgen är inte enligt mockupen. 
Och när man klickar på loggan kommer man till orderstatus, vi förstår inte logiken i det, kanske bättre att komma till menyn eller liknande istället

**Comment by maxaakre** [comment]
Det ska vara så om vi lyckades med allt i VG kriterierna
vi har inte fått något bestämt vad jag vet

**Comment by kogl** [comment]
fixat
